#
control_dt: 0.02

msg_type: "hg"     # "hg" or "go"
imu_type: "pelvis"    # "torso" or "pelvis"

lowcmd_topic: "rt/lowcmd"
lowstate_topic: "rt/lowstate"

policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/policy.onnx"     #修改路径

#leg_joint2motor_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 15,16 ,17 ,18, 22, 23 ,24 ,25]

#kps: [100, 100, 100, 150, 40, 40, 100, 100, 100, 150, 40, 40]
#kds: [2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2]
# kps: [200., 150., 150., 200.,  40.,  40., 200., 150., 150., 200.,  40.,  40.,
#         200.,  100.,  100.,  100.,  40.,  100.,  100.,  100.,  40.]
# kds: [4., 3., 3., 4., 2., 2., 4., 3., 3., 4., 2., 2.,
#       2.,
#       2., 2., 2., 2.,
#       2., 2., 2., 2.]

# kps: [100, 100, 100, 150.,  20.,  20., 100, 100, 100, 150., 20.,  20.,
#         200.,  90.,  60.,  20.,  60.,  90.,  60.,  20.,  60.]
# kds: [2., 2., 2., 4., 2., 2., 2., 2., 2., 4., 2., 2., 5., 2., 2., 2., 2., 2.,
#         2., 2., 2.]
#kps: [200, 150, 150, 200.,  20.,  20., 200, 150, 150, 200.,  20.,  20.,
#        200.,  90.,  60.,  20.,  60.,  90.,  60.,  20.,  60.]
#kds: [5., 5., 5., 5., 2., 2., 5., 5., 5., 5., 2., 2., 5., 2., 2., 2., 2., 2.,
#        2., 2., 2.]
#

# TODO：修改leg motor idx
leg_joint2motor_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
# TODO：修改了pd，按照此代码框架把上肢和腿部的分开
kps: [100, 100, 100, 150, 40, 40,
      100, 100, 100, 150, 40, 40,
]
kds: [2, 2, 2, 4, 2, 2,
      2, 2, 2, 4, 2, 2,
]
# TODO：修改了default angles，腿部的
default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
                 -0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
]

#default_angles: [-0.1,  0.0,  0.0,  0.3, -0.2, 0.0,
#                  -0.1,  0.0,  0.0,  0.3, -0.2, 0.0]

#this old
# default_angles: [-0.312,  0.0,  0.0,  0.669, -0.363, 0.0,
#                   -0.312,  0.0,  0.0,  0.669, -0.363, 0.0,0.,0.35,0.16,0,0.87,0.35,-0.16,0,0.87]

#NEW
#default_angles: [-0.2,  0.0,  0.0,  0.42, -0.23, 0.0,
#                  -0.2,  0.0,  0.0,  0.42, -0.23, 0.0,0.,0.35,0.18,0,0.87,0.35,-0.18,0,0.87]

# default_angles: [-0.2,  0.0,  0.0,  0.42, -0.23, 0.0,
#                   -0.2,  0.0,  0.0,  0.42, -0.23, 0.0,0.,0.35,0.16,0,0.87,0.35,-0.16,0,0.87]


#arm_waist_joint2motor_idx: [12, 13, 14,
#                            15, 16, 17, 18, 19, 20, 21,
#                            22, 23, 24, 25, 26, 27, 28]

# 原来的
#arm_waist_joint2motor_idx: [ 13, 14,
#                            19, 20, 21,
#                            26, 27, 28]

# TODO：改的，顺序按照xml文件里的motor顺序
arm_waist_joint2motor_idx: [12,
                            13, 14, 15, 16, 17, 18, 19,
                            20, 21, 22, 23, 24, 25, 26
]
arm_waist_kps: [300,
                200, 200, 200, 100, 20, 20, 20,
                200, 200, 200, 100, 20, 20, 20
]

arm_waist_kds: [5,
                4, 4, 4, 1, 0.5, 0.5, 0.5,
                4, 4, 4, 1, 0.5, 0.5, 0.5
]

arm_waist_target: [0.0,
                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
]

ang_vel_scale: 0.5
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.5]
num_actions: 12
num_obs: 76 #74
num_obs_frame: 6 #10
num_dofs: 27

max_cmd: [0.6, 0.5, 1.57]